apiVersion:              apps/v1
kind:                    Deployment
metadata:
  name:                  tango-nodejs-deployment
spec:
  selector:
    matchLabels:
      app:               tango
  # replicas:              3
  template:
    metadata:
      labels:
        app:             tango
    spec:
      containers:
      - name:            tango
        image:           tango-nodejs
        imagePullPolicy: Never
        ports:
        - containerPort: 80
