apiVersion:       v1
kind:             Service
metadata:
  name:           tango-nodejs-service
  labels:
    app:          tango
spec:
  selector:
    app:          tango
  ports:
    - protocol:   TCP
      port:       8100 # 抽象的 Service 端口，可以使任何其它 Pod 访问该 Service 的端口
      targetPort: 80 # 容器接收流量的端口
      nodePort:   32333
  type:           NodePort
