version: 2.1
jobs:
  build-nodejs:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          command: cd legacy-nodejs && make build

  build-python:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          command: cd python && make deps
workflows:
  tango:
    jobs:
      - build-nodejs
      - build-python
