version: 2.1
jobs:
  build-nodejs:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          command: cd legacy-nodejs && make build
  build-python:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          command: |
            cd python
            python3 -m venv venv
            . venv/bin/activate
            make deps
  test-python:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          command: |
            cd python
            python3 -m venv venv
            . venv/bin/activate
            make deps
            make lint
            make test
workflows:
  tango:
    jobs:
      - build-nodejs
      - build-python
      - test-python:
          requires:
            - build-python
