apiVersion:              apps/v1
kind:                    Deployment
metadata:
  name:                  tango-python-deployment
spec:
  selector:
    matchLabels:
      app:               tango-python
  # replicas:              1
  template:
    metadata:
      labels:
        app:             tango-python
    spec:
      containers:
      - name:            tango-python
        image:           tango-python
        imagePullPolicy: Never
        ports:
        - containerPort: 80
