apiVersion:       v1
kind:             Service
metadata:
  name:           tango-python-service
  labels:
    app:          tango-python
spec:
  selector:
    app:          tango-python
  ports:
    - protocol:   TCP
      port:       8888
      targetPort: 80
      nodePort:   32000
  type:           NodePort
